/**
 * scripts/generate-wallets.ts
 *
 * Generates all wallets needed for GenesisToken deployment:
 *   - deployer    (pays gas, deploys contract)
 *   - admin       (DEFAULT_ADMIN_ROLE, MINTER_ROLE, PAUSER_ROLE)
 *   - treasury    (receives 85% / 8.5B vesting alloc)
 *   - ecosystem   (receives 5% / 500M for rewards & grants)
 *   - team        (receives 5% / 500M on 2-yr vesting)
 *   - liquidity   (receives 5% / 500M for LP at launch)
 *
 * Outputs a ready-to-use .env and wallets.json.
 * KEY MATERIAL IS SENSITIVE — keep wallets.json out of git.
 *
 * Usage:
 *   npx hardhat run scripts/generate-wallets.ts --network hardhat
 */

import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

interface WalletInfo {
  label: string;
  address: string;
  privateKey: string;
  mnemonic?: string;
  purpose: string;
  initialPOL?: string;
}

function makeWallet(label: string, purpose: string): WalletInfo {
  const w = ethers.Wallet.createRandom();
  return {
    label,
    address: w.address,
    privateKey: w.privateKey,
    mnemonic: (w as any).mnemonic?.phrase ?? undefined,
    purpose,
  };
}

async function main() {
  console.log("\n══════════════════════════════════════════════════");
  console.log("  Genesis World Token — Wallet Generator");
  console.log("══════════════════════════════════════════════════\n");

  // ── Generate all wallets ──────────────────────────────────────────────
  const wallets: WalletInfo[] = [
    makeWallet(
      "deployer",
      "Pays gas to deploy contracts. Needs ~1 POL on Polygon mainnet.",
    ),
    makeWallet(
      "admin",
      "Holds DEFAULT_ADMIN_ROLE, MINTER_ROLE, PAUSER_ROLE. Cold wallet recommended.",
    ),
    makeWallet(
      "treasury",
      "Receives 8,500,000,000 GENESIS (85%) on 3-year linear vesting.",
    ),
    makeWallet(
      "ecosystem",
      "Receives 500,000,000 GENESIS (5%) for agent rewards, staking, grants.",
    ),
    makeWallet("team", "Receives 500,000,000 GENESIS (5%) on 2-year linear vesting."),
    makeWallet(
      "liquidity",
      "Receives 500,000,000 GENESIS (5%) for liquidity provision at launch.",
    ),
  ];

  // ── Display ────────────────────────────────────────────────────────────
  for (const w of wallets) {
    console.log(`  ── ${w.label.toUpperCase()} ──`);
    console.log(`     Address:     ${w.address}`);
    console.log(`     Purpose:     ${w.purpose}`);
    console.log();
  }

  // ── Write wallets.json (SENSITIVE — gitignored) ───────────────────────
  const walletsPath = path.join(__dirname, "..", "wallets.json");
  const walletsData = {
    generated: new Date().toISOString(),
    warning: "SENSITIVE — never commit this file. Store each private key in a hardware wallet or secrets manager.",
    wallets: wallets.map((w) => ({
      label: w.label,
      address: w.address,
      privateKey: w.privateKey,
      mnemonic: w.mnemonic,
      purpose: w.purpose,
    })),
  };
  fs.writeFileSync(walletsPath, JSON.stringify(walletsData, null, 2));
  console.log(`  ✓ Wallet key material saved → wallets.json`);
  console.log(`    (gitignored — back this up in a password manager NOW)\n`);

  // ── Write .env ─────────────────────────────────────────────────────────
  const deployer = wallets.find((w) => w.label === "deployer")!;
  const admin    = wallets.find((w) => w.label === "admin")!;
  const treasury = wallets.find((w) => w.label === "treasury")!;
  const ecosystem= wallets.find((w) => w.label === "ecosystem")!;
  const team     = wallets.find((w) => w.label === "team")!;
  const liquidity= wallets.find((w) => w.label === "liquidity")!;

  const envContent = `# Genesis Contracts — Auto-generated by generate-wallets.ts
# Generated: ${new Date().toISOString()}
# NEVER commit this file. It is .gitignored.

# ── RPC / API keys ────────────────────────────────────────────────────
# Set your Alchemy/Infura URL here — NEVER hardcode API keys in source code
POLYGON_RPC_URL=
AMOY_RPC_URL=https://rpc-amoy.polygon.technology
POLYGONSCAN_API_KEY=

# ── Deployer (needs ~1 POL for gas) ──────────────────────────────────
DEPLOYER_PRIVATE_KEY=${deployer.privateKey}
# Deployer address: ${deployer.address}

# ── Contract role addresses ───────────────────────────────────────────
GENESIS_ADMIN=${admin.address}
GENESIS_TREASURY=${treasury.address}
GENESIS_ECOSYSTEM=${ecosystem.address}
GENESIS_TEAM=${team.address}
GENESIS_LIQUIDITY=${liquidity.address}
`;

  const envPath = path.join(__dirname, "..", ".env");
  fs.writeFileSync(envPath, envContent);
  console.log(`  ✓ .env written with all addresses and deployer key\n`);

  // ── Funding instructions ────────────────────────────────────────────
  console.log("══════════════════════════════════════════════════");
  console.log("  NEXT STEP — Fund the Deployer Wallet with POL");
  console.log("══════════════════════════════════════════════════");
  console.log();
  console.log(`  Deployer address: ${deployer.address}`);
  console.log();
  console.log("  Send at least 1 POL (Polygon mainnet) to this address.");
  console.log("  POL is needed for gas to deploy the contract.");
  console.log();
  console.log("  Where to get POL:");
  console.log("    • Coinbase, Binance, Kraken → withdraw as MATIC/POL to Polygon network");
  console.log("    • Bridge from Ethereum: https://portal.polygon.technology/bridge");
  console.log("    • Use existing Polygon wallet → send to deployer address above");
  console.log();
  console.log("  After funding, run:");
  console.log("    npx hardhat run scripts/deploy.ts --network polygon");
  console.log();
  console.log("  Or run the full automation:");
  console.log("    .\\setup.ps1");
  console.log("══════════════════════════════════════════════════\n");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
